//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulaqCMS.RazorTemplate
{
    using System;
    using BulaqCMS.Models;
    
    
    public class _8fb057bf_607e_40b5_9bef_8b2ebebbcb60 : BulaqCMS.RazorTemplate.IndexTemplate
    {
        
#line hidden
        
        public _8fb057bf_607e_40b5_9bef_8b2ebebbcb60()
        {
        }
        
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<!-- saved from url=(0023)http://mouse.arzu3.com/ -->\r\n<html");

WriteLiteral(" lang=\"zh-CN\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=UTF-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>\r\n");

WriteLiteral("        ");

   Write(Dics["title"]);

WriteLiteral("\r\n    </title>\r\n    <meta");

WriteLiteral(" name=\"robots\"");

WriteLiteral(" content=\"noindex,follow\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        window._wpemojiSettings = {""baseUrl"":""http:\/\/s.w.org\/images\/core\/emoji\/72x72\/"",""ext"":"".png"",""source"":{""concatemoji"":""http:\/\/mouse.arzu3.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.3.1""}};
        !function(a,b,c){function d(a){var c=b.createElement(""canvas""),d=c.getContext&&c.getContext(""2d"");return d&&d.fillText?(d.textBaseline=""top"",d.font=""600 32px Arial"",""flag""===a?(d.fillText(String.fromCharCode(55356,56812,55356,56807),0,0),c.toDataURL().length>3e3):(d.fillText(String.fromCharCode(55357,56835),0,0),0!==d.getImageData(16,16,1,1).data[0])):!1}function e(a){var c=b.createElement(""script"");c.src=a,c.type=""text/javascript"",b.getElementsByTagName(""head"")[0].appendChild(c)}var f,g;c.supports={simple:d(""simple""),flag:d(""flag"")},c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.simple&&c.supports.flag||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener(""DOMContentLoaded"",g,!1),a.addEventListener(""load"",g,!1)):(a.attachEvent(""onload"",g),b.attachEvent(""onreadystatechange"",function(){""complete""===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);
    </script>
    <script");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/wp-emoji-release.min.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        img.wp-smiley,
        img.emoji {
            display: inline !important;
            border: none !important;
            box-shadow: none !important;
            height: 1em !important;
            width: 1em !important;
            margin: 0 .07em !important;
            vertical-align: -0.1em !important;
            background: none !important;
            padding: 0 !important;
        }
    </style>
    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" id=\"crayon-css\"");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/crayon.min.css\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"all\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"css/classic.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" id=\"crayon-theme-classic-css\"");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/classic.css\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"all\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"/Template/default/css/vs2012-black.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" id=\"crayon-theme-vs2012-black-css\"");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/vs2012-black.css\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"all\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"/Template/default/css/monaco.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" id=\"crayon-font-monaco-css\"");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/monaco.css\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"all\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"/Template/default/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" id=\"Always-style-css\"");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/style.css\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" media=\"screen\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/jquery.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/jquery-migrate.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/ug_vk.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        /* <![CDATA[ */
        var CrayonSyntaxSettings = {""version"":""2.7.1"",""is_admin"":""0"",""ajaxurl"":""http:\/\/mouse.arzu3.com\/wp-admin\/admin-ajax.php"",""prefix"":""crayon-"",""setting"":""crayon-setting"",""selected"":""crayon-setting-selected"",""changed"":""crayon-setting-changed"",""special"":""crayon-setting-special"",""orig_value"":""data-orig-value"",""debug"":""""};
        var CrayonSyntaxStrings = {""copy"":""Press %s to Copy, %s to Paste"",""minimize"":""Click To Expand Code""};
        /* ]]> */
    </script>
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/crayon.min.js\"");

WriteLiteral("></script>\r\n    <link");

WriteLiteral(" rel=\"EditURI\"");

WriteLiteral(" type=\"application/rsd+xml\"");

WriteLiteral(" title=\"RSD\"");

WriteLiteral(" href=\"http://mouse.arzu3.com/xmlrpc.php?rsd\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"wlwmanifest\"");

WriteLiteral(" type=\"application/wlwmanifest+xml\"");

WriteLiteral(" href=\"http://mouse.arzu3.com/wp-includes/wlwmanifest.xml\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"generator\"");

WriteLiteral(" content=\"WordPress 4.3.1\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/share.js\"");

WriteLiteral("></script>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"http://bdimg.share.baidu.com/static/api/css/share_style1_24.css\"");

WriteLiteral(">\r\n</head>\r\n<body");

WriteLiteral(" class=\"rtl home blog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"Mouse_quotes\"");

WriteLiteral(">ئاتا - ئانىدىن يامانلىغان ئەقىلنىڭ يوقلىقى، تاماقتىن يامانلىغان قورساقنىڭ توقلۇق" +
"ى.</div>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">var slidei = 0;var slidescode = new Array();slidescode[1] = 'ئابروي ئەقىلدىن كېلەر، ئېغىزدىن كېتەر.';slidescode[2] = 'ئاتا - ئانا چۈمۈلىدەك يىغار، بالا توخۇدەك چاچار.';slidescode[3] = 'ئاتا - ئاناڭدىن مىراس قالسۇن دېسەڭ، ھۈنىرىڭگە ئىخلاس قىل.';slidescode[4] = 'ئاتا - ئاناڭغا چىنىدە بەرسەڭ، پەرزەنتىڭ ساڭا تاغارلاپ بېرەر.';slidescode[5] = 'ئاتا - ئاناڭغا نېمە قىلساڭ، بالىلىرىڭدىن شۇنى كۆرىسەن.';slidescode[6] = 'ئاتا - ئاناڭنى باقمىساڭ، بالاڭدىن تەما قىلما.';slidescode[7] = 'ئاتا - ئاناڭنىڭ ھۆرمىتىنى قىل، خەلقىڭنىڭ خىزمىتىنى قىل.';slidescode[8] = 'ئاتا - ئانام بولسىكەن، ئاغزى- بۇرنى بولمىسىكەن.';slidescode[9] = 'ئاتا - ئانا يايرىسا باغ، يۆلەنسە تاغ.';slidescode[10] = 'ئاتا - ئانىدىن يامانلىغان ئەقىلنىڭ يوقلىقى، تاماقتىن يامانلىغان قورساقنىڭ توقلۇقى.';function slidecode(){slidei = slidei + 1;if(slidei > 10) slidei=1;document.getElementById('Mouse_quotes').innerHTML = slidescode[slidei];setTimeout(""slidecode()"",10000);};setTimeout(""slidecode()"",10000);</script>
    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"logo\"");

WriteLiteral("> <a");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/چاشقان تورخاتىرسى.html\"");

WriteLiteral(" title=\"چاشقان تورخاتىرسى\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/logo.png\"");

WriteLiteral(" alt=\"چاشقان تورخاتىرسى\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/themes/mouse/images/logo.png\"");

WriteLiteral(@"></a></div>
            <!--<div class=""teshwiqat""><a href=""http://bbs.xjcfan.com/thread-4346-1-1.html"" target=""_blank""><img src=""http://mouse.arzu3.com/wp-content/themes/mouse/images/760x90.png"" alt=""كومپيۇتېر ھەۋەسكارلىرى چەكلىك شىركىتى"" original=""http://mouse.arzu3.com/wp-content/themes/mouse/images/760x90.png""></a></div>-->
            <div");

WriteLiteral(" id=\"main-nav\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navicon\"");

WriteLiteral(">\r\n                </div>\r\n                <ul");

WriteLiteral(" id=\"menu\"");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" id=\"menu-item-563\"");

WriteLiteral(" class=\"menu-item menu-item-type-custom menu-item-object-custom current-menu-item" +
" current_page_item menu-item-home menu-item-563\"");

WriteLiteral("><a");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/چاشقان تورخاتىرسى.html\"");

WriteLiteral(">باش بەت</a></li>\r\n                    <li");

WriteLiteral(" id=\"menu-item-543\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has" +
"-children menu-item-543\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=2\"");

WriteLiteral(">پىروگرامما    »</a>\r\n                        <ul");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" id=\"menu-item-547\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-547" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=3\"");

WriteLiteral(">VB.NET</a></li>\r\n                            <li");

WriteLiteral(" id=\"menu-item-545\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-545" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=6\"");

WriteLiteral(">HTML5&amp;CSS3</a></li>\r\n                            <li");

WriteLiteral(" id=\"menu-item-546\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-546" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=9\"");

WriteLiteral(">Office VBA</a></li>\r\n                            <li");

WriteLiteral(" id=\"menu-item-633\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-633" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=10\"");

WriteLiteral(">Windows phone</a></li>\r\n                            <li");

WriteLiteral(" id=\"menu-item-562\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-562" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=1\"");

WriteLiteral(">++C</a></li>\r\n                            <li");

WriteLiteral(" id=\"menu-item-1616\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-161" +
"6\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=25\"");

WriteLiteral(">ماتېماتىكا</a></li>\r\n                            <li");

WriteLiteral(" id=\"menu-item-870\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-870" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=17\"");

WriteLiteral(">Windows Store App</a></li>\r\n                        </ul>\r\n                    <" +
"/li>\r\n                    <li");

WriteLiteral(" id=\"menu-item-1551\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has" +
"-children menu-item-1551\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=22\"");

WriteLiteral(">قىلغانلىرىم    »</a>\r\n                        <ul");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" id=\"menu-item-540\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-540" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=7\"");

WriteLiteral(">ئويلىغانلىرىم</a></li>\r\n                            <li");

WriteLiteral(" id=\"menu-item-541\"");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-541" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=13\"");

WriteLiteral(">تەرجىمەلىرىم</a></li>\r\n                        </ul>\r\n                    </li>\r" +
"\n                    <li");

WriteLiteral(" id=\"menu-item-1145\"");

WriteLiteral(" class=\"menu-item menu-item-type-custom menu-item-object-custom menu-item-1145\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?page_id=1143\"");

WriteLiteral(">جەمگاھ</a></li>\r\n                    <li");

WriteLiteral(" id=\"menu-item-1571\"");

WriteLiteral(" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-1571\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?page_id=1564\"");

WriteLiteral(">ئالاقە</a></li>\r\n                    <li");

WriteLiteral(" id=\"menu-item-629\"");

WriteLiteral(" class=\"menu-item menu-item-type-custom menu-item-object-custom menu-item-629\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com//?feed=rss2\"");

WriteLiteral(">RSS</a></li>\r\n                </ul>  <ul");

WriteLiteral(" id=\"menu-mobi\"");

WriteLiteral(" class=\"menu\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"menu-item menu-item-type-custom menu-item-object-custom current-menu-item" +
" current_page_item menu-item-home menu-item-563\"");

WriteLiteral("><a");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/چاشقان تورخاتىرسى.html\"");

WriteLiteral(">باش بەت</a></li>\r\n                    <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has" +
"-children menu-item-543\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=2\"");

WriteLiteral(">پىروگرامما    »</a>\r\n                        <ul");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-547" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=3\"");

WriteLiteral(">VB.NET</a></li>\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-545" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=6\"");

WriteLiteral(">HTML5&amp;CSS3</a></li>\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-546" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=9\"");

WriteLiteral(">Office VBA</a></li>\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-633" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=10\"");

WriteLiteral(">Windows phone</a></li>\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-562" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=1\"");

WriteLiteral(">++C</a></li>\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-161" +
"6\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=25\"");

WriteLiteral(">ماتېماتىكا</a></li>\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-870" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=17\"");

WriteLiteral(">Windows Store App</a></li>\r\n                        </ul>\r\n                    <" +
"/li>\r\n                    <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has" +
"-children menu-item-1551\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=22\"");

WriteLiteral(">قىلغانلىرىم    »</a>\r\n                        <ul");

WriteLiteral(" class=\"sub-menu\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-540" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=7\"");

WriteLiteral(">ئويلىغانلىرىم</a></li>\r\n                            <li");

WriteLiteral(" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-541" +
"\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?cat=13\"");

WriteLiteral(">تەرجىمەلىرىم</a></li>\r\n                        </ul>\r\n                    </li>\r" +
"\n                    <li");

WriteLiteral(" class=\"menu-item menu-item-type-custom menu-item-object-custom menu-item-1145\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?page_id=1143\"");

WriteLiteral(">جەمگاھ</a></li>\r\n                    <li");

WriteLiteral(" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-1571\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?page_id=1564\"");

WriteLiteral(">ئالاقە</a></li>\r\n                    <li");

WriteLiteral(" class=\"menu-item menu-item-type-custom menu-item-object-custom menu-item-629\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com//?feed=rss2\"");

WriteLiteral(">RSS</a></li>\r\n                </ul>      <form");

WriteLiteral(" role=\"search\"");

WriteLiteral(" method=\"get\"");

WriteLiteral(" id=\"search-form\"");

WriteLiteral(" action=\"./چاشقان تورخاتىرسى_files/چاشقان تورخاتىرسى.html\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"ئىزدەش\"");

WriteLiteral(" name=\"s\"");

WriteLiteral(" id=\"s\"");

WriteLiteral(" onblur=\"if ( this.value == &#39;&#39; ){this.value=&#39;ئىزدەش&#39;;}\"");

WriteLiteral(" onfocus=\"if ( this.value == &#39;ئىزدەش&#39; ){this.value = &#39;&#39;;}\"");

WriteLiteral(">\r\n                </form>\r\n                <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"bottom-bar\"");

WriteLiteral("></div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(">\r\n");

            
             foreach (var post in Posts)
            {

WriteLiteral("                <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                        <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=2000\"");

WriteAttribute("title", Tuple.Create(" title=\"", 13466), Tuple.Create("\"", 13485)
, Tuple.Create(Tuple.Create("", 13474), Tuple.Create<System.Object, System.Int32>(post.Title
, 13474), false)
);

WriteLiteral(">");

                                                                                    Write(post.Title);

WriteLiteral("</a></h1>\r\n                        <span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">");

                                       Write(post.SendTime != null ? post.SendTime.Value.ToString("yyyy-MM-dd") : "");

WriteLiteral("  |    | 229 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=2000#comments\"");

WriteLiteral(">");

                                                                                                                                                                                                Write(post.CommentsCount);

WriteLiteral(" باھا</a></span>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=2000\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/analog-1024x548.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/08/analog-1024x548.jpg\"" +
"");

WriteLiteral("></a>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">قىسقىچە چۈشەندۈرۈش ئوقۇش پۈتكۈزگەندىن كېيىن ئۆيگە يېنىپ كەلدىم. بۇ جەرياندا مەيلى نېمىلا دېمەي، بىلوگ بىرئايدىن كۆپرەك ۋاقىت يېڭىلانمىدى.&nbsp; تۇرمۇش ھەلەكچىلىكىدە بولۇپتىمەن. ئەسلى ئۆزۈمنىڭ پىرىنسىپىدا «تۇرمۇش ھەلەكچىلىك» دېگەن سىپايە ئېچىلغان داستىغاننى ئۆزۈمنى بەزلەش ئۈچۈن باھانە قىلمىسام…</div>
                    </div>
                    <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n                </div>\r\n");

            }

WriteLiteral("            <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1907\"");

WriteLiteral(">Apache Shiro بىخەتەرلىك رامكىسى ھەققىدە</a></h1>\r\n                    <span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-07-16  |    | 217 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1907#comments\"");

WriteLiteral(">5 باھا</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1907\"");

WriteLiteral(" title=\"Apache Shiro بىخەتەرلىك رامكىسى ھەققىدە\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/6-1024x559.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/07/6-1024x559.jpg\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">Apache Shiro بىخەتەرلىك رامكىسى ھەققىدە تەييارلىغۇچى: چاشقان دەسلەپكى بايان Apache Shiro بولسا Java نىڭ بىخەتەرلىك رامكىسى. ھازىر بۇنىڭ ئىشلىتىلىشى بارغانسېرى ئالقىشقا ئېرىشكەن بولۇپ، سەۋەبى، ئۇنى ئىشلىتىش&nbsp;خېلى ئاددىي. Java نىڭ بىخەتەرلىك&nbsp; رامكىسى ئىچىدىكى Spring Security غا…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1982\"");

WriteLiteral(">تەس كەلدى</a></h1>\r\n                    <span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-07-16  |    | 258 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1982#comments\"");

WriteLiteral(">10 باھا</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1982\"");

WriteLiteral(" title=\"تەس كەلدى\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/18adc23a0488ba266ecd9849dc96aa25.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/07/18adc23a0488ba266ecd" +
"9849dc96aa25.jpg\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">تەس كەلدى ئاپتورى: چاشقان كۈتۈپخانىدىن ئايرىلىش تەس كەلدى مەكتەپ كۈتۈپخانىدىن ئاخىرقى رەت ئېغىرلاشقان قەدەملىرىمنى سۆرەپ، كەينىمگە يېنىش- يېنىشلاپ قاراپ، قىيمىغان ھالدا ئاستاغىنە يېنىپ چىقتىم. مېڭەمدە نېمىلەرنىدۇ ئويلايتتىم، لېكىن زادى نېمىلىكىنى زادىلا ئويلاپ تاپالمىدىم؛ بىر نەرسىلەرگە…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1977\"");

WriteLiteral(">[ئىختىيارىي كونترول] رەسىم سۈرگۈچ(Image Slider)</a></h1>\r\n                    <s" +
"pan");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-07-16  |    | 141 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1977#comments\"");

WriteLiteral(">2 باھا</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1977\"");

WriteLiteral(" title=\"[ئىختىيارىي كونترول] رەسىم سۈرگۈچ(Image Slider)\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/slider.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/07/slider.jpg\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">[ئىختىيارىي كونترول] رەسىم سۈرگۈچ(Image Slider) تەييارلىغۇچى: چاشقان قىسقىچە چۈشەنچە مەلۇم سەۋەب تۈپەيلى QQ نى يېڭىلىغاندىن كېيىن ئەڭ ئاخىرىدا يېڭىلىقلارنى تونۇشتۇرۇدىغان رەسىم سۈرگۈچلۈك كۆزنەككە ئوخشايدىغان ئىختىيارىي كونتىرول يېزىشقا ئېھتىياجلىق بولۇپ قالدىم. بۇ كۆزنەكنىڭ ئالاھىدىلىكى شۇكى، بىرقانچە…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1970\"");

WriteLiteral(">كودنى ناھايىتى ئۇزۇن يازغانلىقىڭىزدىن 10 بىشارەت</a></h1>\r\n                    <" +
"span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-07-14  |    | 183 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1970#comments\"");

WriteLiteral(">3 باھا</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1970\"");

WriteLiteral(" title=\"كودنى ناھايىتى ئۇزۇن يازغانلىقىڭىزدىن 10 بىشارەت\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/vocabulary.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/07/vocabulary.jpg\"");

WriteLiteral(" style=\"display: inline;\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">كودنى ناھايىتى ئۇزۇن يازغانلىقىڭىزدىن 10 بىشارەت ئىنگىلىزچىدىن تەرجىمە قىلغۇچى:چاشقان ئەسلى مەنبە: http://www.itworld.com/article/2876757/10-signs-you-ve-been-coding-too-much-for-too-long.html#slide1 پىروگراممېر، كۆپچىلىك ئويلىغىنىدەك، كود يېزىشقا ئامراق. ئۇلار ئۆزلىرىنىڭ تۈرئاخىرقى مۆھلەت قىستاپ كەلگەندە، ئۇلاز ھەتتا ئاندا- ساندا كۆپ ۋاقىت كومپيۇتېرغا قاراپ مەس بولغان ھالدا…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1955\"");

WriteLiteral(">ئۇيغۇرچە OCR ھەققىدە مېنىڭ تەجرىبىلىرىم (1)</a></h1>\r\n                    <span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-07-14  |    | 203 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1955#comments\"");

WriteLiteral(">2 باھا</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1955\"");

WriteLiteral(" title=\"ئۇيغۇرچە OCR ھەققىدە مېنىڭ تەجرىبىلىرىم (1)\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/OCR_BinImage.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/07/OCR_BinImage.jpg\"");

WriteLiteral(" style=\"display: inline;\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">ئۇيغۇرچە OCR ھەققىدە مېنىڭ تەجرىبىلىرىم (1) ئاپتورى:Mars 3(بىلوگىمىزنىڭ تەكلىپلىك ئەزاسى ۋە ئوقۇرمىنى) ئىلاۋە: مەزكۇر ماقالە ئاپتورنىڭ ھاۋالىسى بىلەن قايتا- قايتا ئويلىنىش ئارقىلىق بۇ بىلوگقا يوللاندى ئالاھىدە بىرەر سەۋەب بولۇپ قالمىسىلا، مەزكۇر مەزمۇن داۋاملىق سۆزلىنىدۇ ۋە…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1938\"");

WriteLiteral(">Javascript دا LINQ دىن مىسال(كۈچلۈك تەۋسىيە)</a></h1>\r\n                    <span" +
"");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-07-01  |    | 167 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1938#respond\"");

WriteLiteral(">دېۋان</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1938\"");

WriteLiteral(" title=\"Javascript دا LINQ دىن مىسال(كۈچلۈك تەۋسىيە)\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/b28988c44347a2eb71d529bdfa0301a8.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/07/b28988c44347a2eb71d5" +
"29bdfa0301a8.jpg\"");

WriteLiteral(" style=\"display: inline;\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">Javascript دا LINQ دىن مىسال ئىنگىلىزچىدىن تەرجىمە قىلغۇچى:چاشقان ئەسلى مەنبە:http://www.codeproject.com/Articles/603742/LINQ-for-JavaScript چۈشەندۈرۈش LINQ(Language INtegrated Query) بولسا بىر گۇرۇپپا C# ۋە VB.net تىللىرىغا ئىشلىتىلىدىغان تىل كېڭەيتمىسى. ئۇ C# ياكى VB.net كودلىرىنى سانداندىن ئىزدەشتە ئوخشاش شەكىلدىكى ئىچكى ساقلىغۇچ…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1913\"");

WriteLiteral(">كىتاب ئىئانە قىلىندى</a></h1>\r\n                    <span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-06-24  |    | 244 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1913#comments\"");

WriteLiteral(">4 باھا</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1913\"");

WriteLiteral(" title=\"كىتاب ئىئانە قىلىندى\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/book-1024x480.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/06/book-1024x480.jpg\"");

WriteLiteral(" style=\"display: inline;\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">كىتاب ئىئانە قىلىندى ئالدى بىلەن ئۇلۇغ، بەرىكەتلىك رامىزان كۈنلىرىدە ھەربىرىمىزنىڭ ساق- سالەمەت، ئىشلىرى ئوڭۈشلۇق بولۇشىنى تىلەيمەن شۇنىڭ بىلەن بىرگە چەكسىز شۈكرىلەرنى ئېيتىش بىلەن تېمنى باشلايمەن. ئالدىنقى قېتىم مۇنداق بىر ئىشنى پىلانلىدىم ناملىق تېمىدا مەكتەپ كۈتۈپخانىسىغا…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1903\"");

WriteLiteral(">Facebook توپلاشتۇرۇلغان ئېچىش مۇھىتى Nuclide  نى ئوچۇق مەنبەلىك قىلدى</a></h1>\r\n" +
"                    <span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-06-24  |    | 154 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1903#respond\"");

WriteLiteral(">دېۋان</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1903\"");

WriteLiteral(" title=\"Facebook توپلاشتۇرۇلغان ئېچىش مۇھىتى Nuclide  نى ئوچۇق مەنبەلىك قىلدى\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/20150624122407763.gif\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/06/20150624122407763.gi" +
"f\"");

WriteLiteral(" style=\"display: inline;\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">Facebook توپلاشتۇرۇلغان ئېچىش مۇھىتى Nuclide&nbsp; نى ئوچۇق مەنبەلىك قىلدى مەن ئادەتتە تەھرىرلىگۈچ ئۈچۈن Sublime Text 3 نى ئىشلىتىمەن،&nbsp;مەيلى ئارايۈزى بولسۇن، مەيلى كود تەھرىرلەشتە بولسۇن&nbsp;ئۇتۇقلۇق چىققان تەھرىرلىگۈچ دەپ قارايمەن. Facebook مۇ ئۆزىنىڭ تەھرىرلىگۈچىسى Nuclide IDE نى…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>    <div");

WriteLiteral(" class=\"entry-home\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"entry-head\"");

WriteLiteral(">\r\n                    <h1><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1897\"");

WriteLiteral(">VB6.0 ۋە VB.Net سىلىشتۇرما جەدىۋىلى</a></h1>\r\n                    <span");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">2015-06-23  |    | 248 قىتىم كۆرۈلدى |  <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1897#comments\"");

WriteLiteral(">3 باھا</a></span>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"entry-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"thumb\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1897\"");

WriteLiteral(" title=\"VB6.0 ۋە VB.Net سىلىشتۇرما جەدىۋىلى\"");

WriteLiteral("><img");

WriteLiteral(" src=\"./چاشقان تورخاتىرسى_files/vb.net_-1024x477.jpg\"");

WriteLiteral(" original=\"http://mouse.arzu3.com/wp-content/uploads/2015/06/vb.net_-1024x477.jpg" +
"\"");

WriteLiteral(" style=\"display: inline;\"");

WriteLiteral("></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">VB6.0 ۋە VB.Net سىلىشتۇرما جەدىۋىلى توپلىغۇچى:چاشقان قىسقىچە بايان Basic تىلى دۇنياغا كەلگىلىمۇ 50 يىلدىن ئارتۇق ۋاقىت بولدىغۇ دەيمەن، بىل گەيتېسمۇ ئىشنى Basic تىلىدىن باشلاپتىكەن.بۇنى تىلغا ئېلىشىم ھەرگىزمۇ VB6.0 ئۆگىنىۋاتقان دوسلىرىمنىڭ مۇشۇ تىل بىلەن جاھىللىق بىلەن…</div>
                </div>
                <div");

WriteLiteral(" class=\"entry-foot\"");

WriteLiteral("></div>\r\n            </div>      <div");

WriteLiteral(" class=\"page-nav\"");

WriteLiteral(">\r\n                <ol");

WriteLiteral(" class=\"page-navigator\"");

WriteLiteral("><li");

WriteLiteral(" class=\"prev\"");

WriteLiteral("></li><li");

WriteLiteral(" class=\"current\"");

WriteLiteral("><span>1</span></li><li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?paged=2\"");

WriteLiteral(">2</a></li><li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?paged=3\"");

WriteLiteral(">3</a></li><li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?paged=4\"");

WriteLiteral(">4</a></li><li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?paged=5\"");

WriteLiteral(">5</a></li><li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?paged=6\"");

WriteLiteral(">6</a></li><li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?paged=7\"");

WriteLiteral(">7</a></li><li><span> ... </span></li><li");

WriteLiteral(" class=\"next\"");

WriteLiteral("><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?paged=2\"");

WriteLiteral(">كېيىنكى بەت</a></li></ol>  <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n            </div>\r\n\r\n        </div><!--container-->\r\n        <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"footer-widgets\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"links widget\"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"wiget-title\"");

WriteLiteral(">دوستانە ئۇلىنىش</h3>\r\n                    <ul>\r\n                        <li><a");

WriteLiteral(" href=\"http://teshna.me/\"");

WriteLiteral(" title=\"Teshna.me\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">تەشنا بلوگى</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"http://www.alimahat.com/\"");

WriteLiteral(" title=\"ئالىم ئەھەد تور خاتىرىسى\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">ئالىم ئەھەد تور خاتىرىسى</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"http://www.bilig.cc/\"");

WriteLiteral(" title=\"دەرسخانا\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">بىلىگ دەرسخانىسى</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"http://www.elierkin.com/blog\"");

WriteLiteral(" title=\"ئەپ ئاچقۇچى\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">سارۋان بىلوگى</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"http://www.arzu3.com/\"");

WriteLiteral(" title=\"Arzu\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">قۇرداشلار كىتابخانىسى</a></li>\r\n                    </ul>\r\n                </div" +
">\r\n                <div");

WriteLiteral(" class=\"rand widget\"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"wiget-title\"");

WriteLiteral(">تاغدىن - باغدىن</h3>\r\n                    <ul>\r\n                        <li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1598\"");

WriteLiteral(">بىلوگ سەھىپىسى ئازراق تەڭشەلدى</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1522\"");

WriteLiteral(">ئىككى پروگراممېر ھەققىدە مەسەل</a></li>\r\n                        <li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=781\"");

WriteLiteral(">دەرسىلىك خاتىرىسى- ساندان چۈشەنچىسى ۋە Access2013 نى ئۇلاش(تەۋسىيە)</a></li>\r\n  " +
"                      <li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1064\"");

WriteLiteral("> MS Word قا قۇرئان قىستۇرمىسى(ھەل قىلىندى)</a></li>\r\n                        <li" +
"><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=195\"");

WriteLiteral(">پىروگرامما ئۆگەنگۈچىلەر ئۈچۈن تەكلىپلىرىم</a></li>\r\n                    </ul>\r\n " +
"               </div>\r\n                <div");

WriteLiteral(" class=\"new-comments widget\"");

WriteLiteral(">\r\n                    <h3");

WriteLiteral(" class=\"wiget-title\"");

WriteLiteral(">يىقىنقى باھالار</h3>\r\n                    <ul>\r\n                        <li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?page_id=1143#comment-24946\"");

WriteLiteral(" title=\"جەمگاھ\"");

WriteLiteral(">نامسىز : رەھمەت سىزگە ، مەنمۇ پىروگىراممىغا بەك قىزىققاچقا 9 يىل بوپتۇ پىروگىرام" +
"ما بىلەن ئېتىشىۋاتقىلى ، يا بىر تۈزۈك نەتىجە يوق</a></li>\r\n                     " +
"   <li><a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=2000#comment-24945\"");

WriteLiteral(" title=\"VB.net دا ئىستىرىلكىلىق سائەت\"");

WriteLiteral(">نامسىز : مەنمۇ كۈندە دىگۈدەك كىرىمەن ، يىڭى مەزمۇنلارنى ئىزدەپ ، ئاخىرى ھەرنىمە " +
"بولسا يەنە ئازراق ۋاقىت چىقىرىپسىز .... يازمىلىرىڭىزغا تەقەززارمىز ............<" +
"/a></li>\r\n                        <li>\r\n                            <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1982#comment-24942\"");

WriteLiteral(" title=\"تەس كەلدى\"");

WriteLiteral(@">
                                ئالۋۇن : ئەمدى ماڭىدىغان يۇلىڭىز باشقا ، ئەمدى تۇرمۇشنىڭ ئەگرى تۇقايلىرىدا ياشايسىز ، سىزگە قۇرۇلغان ھەر خىل قىسماقلارمۇ بار تىخى ...
                                سىزگە ئۇتۇق يار بولسۇن !
                            </a>
                        </li>
                        <li>
                            <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=2000#comment-23363\"");

WriteLiteral(" title=\"VB.net دا ئىستىرىلكىلىق سائەت\"");

WriteLiteral(@">
                                يەزرشاھ : بىر دېتال تۈزۋاتقان، ئۈستىگە رەقەملىك سائەتنىڭ ئورنىغا بۇنى قىستۇرسام تېخىمۇ كۆركەم چىققۇدەك. كۆپ رەھمەت.
                                بولسا Chart كونتىرولى ئارقىلىق سىتاتىسكىلاشنىڭ ئاددىي مىسالى بولسا ئالغاچ كەلگەن بولسىڭىز، كۆپ رەھمەت.
                            </a>
                        </li>
                        <li>
                            <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=2000#comment-23188\"");

WriteLiteral(" title=\"VB.net دا ئىستىرىلكىلىق سائەت\"");

WriteLiteral(@">
                                ئەكبەر ئۆزخان : ئەسسالامۇ ئەلەيكۇم !!ياخشىمۇ سىز !!!
                                مەكتەپ مەشخۇلاتىنى باشقۇرۇشقا ئائىت مەزمۇنلاردىكى مەسىللەردىن مىسال قىلىپ ئىشلەپ كۆرىستىپ بەرگەن بولسىڭىز ... تەشەككۇررررررررررررر!!!!
                            </a>
                        </li>
                    </ul>
                </div>
                <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"copyright\"");

WriteLiteral(">\r\n                Copyright ©\r\n                <a");

WriteLiteral(" title=\"چاشقان تورخاتىرسى\"");

WriteLiteral(" href=\"./چاشقان تورخاتىرسى_files/چاشقان تورخاتىرسى.html\"");

WriteLiteral(">چاشقان تورخاتىرسى</a>  |   |\r\n                Theme by <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"http://doghap.net/\"");

WriteLiteral(">Doghap</a>   |\r\n                <a");

WriteLiteral(" href=\"https://ug.wordpress.org/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" title=\"Powered by WordPress\"");

WriteLiteral(">WordPress</a>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"backtop\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"javascript:void();\"");

WriteLiteral(" title=\"ئۈستىگە قايتىش\"");

WriteLiteral(" class=\"scroll_t\"");

WriteLiteral(">&nbsp;</a>\r\n                <a");

WriteLiteral(" href=\"http://mouse.arzu3.com/?p=1326\"");

WriteLiteral(" title=\"بۇ نىمە؟\"");

WriteLiteral(" class=\"to_rand\"");

WriteLiteral(">&nbsp;</a>\r\n                <a");

WriteLiteral(" href=\"javascript:void();\"");

WriteLiteral(" title=\"ئاستىغا قايتىش\"");

WriteLiteral(" class=\"scroll_b\"");

WriteLiteral(">&nbsp;</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <!--wrapper-->\r\n" +
"</body>\r\n</html>\r\n");

        }
    }
}
